development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: crm_development_with_devise
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: crm_test_with_devise
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: crm_production_with_devise
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock